### ISSUE TITLE
The command line version of this doesn't replace plurals with other.

### ISSUE THREAD

**Issue by dessalines** [i18next/i18next-v4-format-converter#1]
![image](https://user-images.githubusercontent.com/930215/137643932-b678e90d-51e4-4f7a-ab5e-fa7808223661.png)

**Comment by adrai** [comment]
Can you please provide a reproducible example or a failing test here: https://github.com/i18next/i18next-v4-format-converter/blob/main/test/converter.spec.js

![image](https://user-images.githubusercontent.com/1086194/137645510-7b91a2be-824b-4b58-8320-bd06d5c6b658.png)

**Comment by dessalines** [comment]
I tested, and its only failing with your bin version published on npm.

`npm install -g i18next-v4-format-converter`

And run it on 

```json
{
  "user_one": "{{count}} user",
  "user_plural": "{{count}} users"
}
```

**Comment by adrai** [comment]
example:

![image](https://user-images.githubusercontent.com/1086194/137646390-42208837-99af-428d-b094-6300ff6ab529.png)

```json
{
  "user": "{{count}} user",
  "user_plural": "{{count}} users",
  "number_of_posts": "sing post",
  "number_of_posts_plural": "plur post"
}
```

```sh
➜  tmp i18next-v4-format-converter
transformed 1 files: /Users/usr/test-project/tmp
```

```json
{
  "user_one": "{{count}} user",
  "user_other": "{{count}} users",
  "number_of_posts_one": "sing post",
  "number_of_posts_other": "plur post"
}
```

**Comment by dessalines** [comment]
Okay, I set up a reproducible example using docker:

```
git clone https://github.com/dessalines/docker_i18next_converter
docker build  . --progress=plain 
```

You can clearly see that your published version doesn't produce the correct output:

```
#8 [5/7] RUN cat test.json
#8 sha256:0f9b08911ff5613f9884c439978f8529340b7eb546fdd743d390145f80053378
#8 0.679 { "user": "{{count}} user", "user_plural": "{{count}} users" }
#8 DONE 0.7s

#9 [6/7] RUN i18next-v4-format-converter
#9 sha256:3e2a7599e027fc73c644c93308c9473a1fe0bea87294a4242dad17e1cfcb64a2
#9 0.939 transformed 1 files: /test
#9 DONE 1.0s

#10 [7/7] RUN cat test.json
#10 sha256:ff3ba22abd3894fb56ec780b4a96aec5482196305d0d927efc125fe9899fad31
#10 0.723 {
#10 0.723   "user_one": "{{count}} user",
#10 0.723   "user_plural": "{{count}} users"
#10 0.723 }#10 DONE 0.8s
```

**Comment by dobernike** [comment]
![image](https://user-images.githubusercontent.com/26094706/141851793-0da6702c-4f71-4568-99dc-21e2527b5645.png)

[CLI] with 378 files, in languages `ch` or `jp` files _plural was not changed to _other. But on the second attempt, they were changed

**Comment by jawakarD** [comment]
> ![image](https://user-images.githubusercontent.com/26094706/141851793-0da6702c-4f71-4568-99dc-21e2527b5645.png)
> 
> i18next-v4-format-converter -i locales/ transformed 306 files
> 
> [CLI] with 306 files, in languages `ch` or `jp` files _plural was not changed to _other. But on the second attempt, they were changed

For me `_plural` is not changed to `_other` for files in languages `id`, `ja` and `zh`

**Comment by adrai** [comment]
These languages has no _plural suffix at all: https://jsfiddle.net/6bpxsgd4

**Comment by jawakarD** [comment]
Oh yeah understood, I guess we anyway added the `_plural` for other languages with same values.
