### ISSUE TITLE
Single plural languages are not being transformed

### ISSUE THREAD

**Issue by SimeonC** [i18next/i18next-v4-format-converter#2]
See the reproduction here, for me this is primarily to do with Japanese language. https://replit.com/@SimeonC/i18next-v4-transform-error#index.js

From my debugging it's due to this line here and can be fixed by changing it to `< 1` https://github.com/i18next/i18next-v4-format-converter/blob/126cb88646d8c414af591bce9b8bcb16e4121a0b/src/index.js#L289

I'm about to go on holiday till Tuesday next week so I can do a PR for this then if that's OK (or someone else can do it as it's pretty trivial I think).

**Comment by adrai** [comment]
Thank you for your help, v1.0.3 should fix it.

**Comment by SimeonC** [comment]
Wow, fast fix!! Thanks a lot, have confirmed it's working correctly.
