### ISSUE TITLE
Doesn't work with custom pluralSeparator

### ISSUE THREAD

**Issue by igorsantos07** [i18next/i18next-v4-format-converter#4]
## 🚀 Feature Proposal

Either implement a `pluralSeparator` option in the converter, or document that it won't work with custom options like that - in this README, in the online tool and in the [docs](https://www.i18next.com/misc/json-format) (which were the places I saw).

## Motivation

We use `pluralSeparator: '^'` as a way to avoid any weird issue with readable keys (as opposed to code-only keys). There's no tool to automatically convert from v3 to v4 in this scenario.

**Comment by adrai** [comment]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/1086194/235070922-4ebe092c-3b00-41e3-8559-5b17204ae5cf.png">


<img width="521" alt="image" src="https://user-images.githubusercontent.com/1086194/235070883-3092cb39-c1ac-4228-b3ae-a081503f00dc.png">

<img width="804" alt="image" src="https://user-images.githubusercontent.com/1086194/235070980-7f11d50a-fac6-4393-a1f3-3a993aaa4163.png">
