### ISSUE TITLE
Encoded Unicode Characters in Translations are Decoded

### ISSUE THREAD

**Issue by ahilke** [i18next/i18next-v4-format-converter#5]
## 🐛 Bug Report

Passing an encoded unicode character like `\u00A0` into the `i18next-v4-format-converter` decodes that character (" ", an unbreakable space, in this example). As far as I can tell, this happens for any unicode character.

## To Reproduce

Using the [online converter](https://i18next.github.io/i18next-v4-format-converter-web/), the following translation file reproduces the issue (for "en", but presumable for all languages):

```json
{
  "no_break_space": "\u00A0",
  "small_em_dash": "\uFE58" 
}
```

Result:

```json
{
  "no_break_space": " ",
  "small_em_dash": "﹘"
}
```

## Expected behavior

The converter should only affect translation keys and not change translation values in any way. There are various possible reasons to want encoded unicode characters in translation files, e.g. interoperability.

## Your Environment

- [online converter](https://i18next.github.io/i18next-v4-format-converter-web/)
- MacOS 13.5, Safari 16.6

**Comment by adrai** [comment]
that's because of the textarea html element... the module itself does not decode the values... see: https://github.com/i18next/i18next-v4-format-converter/commit/fe790f87192c25af42215f9b66fcf3399fd79f12

**Comment by ahilke** [comment]
Thanks for the swift response! I wasn't aware that this issue was web only, and that the website was a different repository when opening this issue - I found it through this repository, so sorry about that. I would still consider this a minor issue as it could catch somebody off-guard if they don't double-check the result.

Checking the web repository, I also think the `JSON.parse` [here](https://github.com/i18next/i18next-v4-format-converter-web/blob/7567b0c697768375757e88e70a773f1063f657ae/pages/index.js#L14) might cause this behaviour.

**Comment by adrai** [comment]
if you have an idea on how to optimize that, feel free to submit a PR ;-)
