### ISSUE TITLE
Incorrect result from the web converter version

### ISSUE THREAD

**Issue by Abdelalim-dev** [i18next/i18next-v4-format-converter#6]
## 🐛 Bug Report

This is related to the web converter version.
The converted result is not correct.

## To Reproduce
- Go to https://i18next.github.io/i18next-v4-format-converter-web/
- Use the following JSON object as input:

```json
{
  "key": "value",
  "key_0": "none",
  "key_1": "single",
  "key_2": "some"
}
```

The result that I got

```json
{
  "key": "value",
  "key_0": "none",
  "key_1": "single",
  "key_2": "some"
}
```

**Screenshot**
![screenshot](https://i.imgur.com/5wlrNpr.png)

## Expected behavior

I should have received the following result:

```json
{
  "key": "value",
  "key_zero": "none",
  "key_one": "single",
  "key_two": "some"
}
```

## Your Environment
https://i18next.github.io/i18next-v4-format-converter-web/

**Comment by adrai** [comment]
english has no multiple plural forms
