### ISSUE TITLE
Incorrect Plural Forms Mapping for Latvian (lv) Locale

### ISSUE THREAD

**Issue by gusaka** [i18next/i18next-v4-format-converter#7]
## 🐛 Bug Report

The plural forms mapping for the Latvian (lv) locale appears to be incorrect. The current mapping does not correctly convert between CLDR and internal representations.

## To Reproduce
1. Go to https://i18next.github.io/i18next-v4-format-converter-web/
2. Use the following JSON object as input:
```json
{
  "myKey_0": "one key",
  "myKey_1": "other {{count}} keys",
  "myKey_2": "no keys"
}
```
3. Observe the result.

**The result that I got:**
```json
{
  "myKey_one": "one key",
  "myKey_zero": "no keys"
}
```
**Screenshot**
<img width="1714" alt="lv-wrong-convert" src="https://github.com/i18next/i18next-v4-format-converter/assets/13864632/93b5fa16-a714-4d8a-988a-d383ac61235f">

## Expected behavior
I should have received the following result:
```json
{
  "myKey_one": "one key",
  "myKey_other": "other {{count}} keys",
  "myKey_zero": "no keys"
}
```
## Your Environment
URL: [i18next-v4-format-converter-web](https://i18next.github.io/i18next-v4-format-converter-web/)

**Comment by adrai** [comment]
thanks... should be fixed now
